-- =============================================
-- 🌱 Seed Reference Data for TMDB Database
-- =============================================
-- Populates: countries, languages, genres
-- =============================================

-- Countries (most common ISO 3166-1 codes)
INSERT INTO countries (iso_3166_1, english_name, native_name) VALUES
    ('US', 'United States', 'United States'),
    ('GB', 'United Kingdom', 'United Kingdom'),
    ('CA', 'Canada', 'Canada'),
    ('AU', 'Australia', 'Australia'),
    ('FR', 'France', 'France'),
    ('DE', 'Germany', 'Deutschland'),
    ('JP', 'Japan', '日本'),
    ('IN', 'India', 'India'),
    ('IT', 'Italy', 'Italia'),
    ('ES', 'Spain', 'España'),
    ('KR', 'South Korea', '대한민국'),
    ('CN', 'China', '中国'),
    ('BR', 'Brazil', 'Brasil'),
    ('MX', 'Mexico', 'México'),
    ('RU', 'Russia', 'Россия'),
    ('NZ', 'New Zealand', 'New Zealand'),
    ('IE', 'Ireland', 'Éire'),
    ('SE', 'Sweden', 'Sverige'),
    ('NO', 'Norway', 'Norge'),
    ('DK', 'Denmark', 'Danmark'),
    ('HK', 'Hong Kong', '香港'),
    ('TW', 'Taiwan', '台灣'),
    ('SG', 'Singapore', 'Singapore'),
    ('TH', 'Thailand', 'ประเทศไทย'),
    ('MY', 'Malaysia', 'Malaysia'),
    ('ID', 'Indonesia', 'Indonesia'),
    ('PH', 'Philippines', 'Pilipinas'),
    ('VN', 'Vietnam', 'Việt Nam'),
    ('AE', 'United Arab Emirates', 'الإمارات'),
    ('SA', 'Saudi Arabia', 'السعودية'),
    ('IL', 'Israel', 'ישראל'),
    ('TR', 'Turkey', 'Türkiye'),
    ('EG', 'Egypt', 'مصر'),
    ('ZA', 'South Africa', 'South Africa'),
    ('NG', 'Nigeria', 'Nigeria'),
    ('AR', 'Argentina', 'Argentina'),
    ('CL', 'Chile', 'Chile'),
    ('CO', 'Colombia', 'Colombia'),
    ('PE', 'Peru', 'Perú'),
    ('VE', 'Venezuela', 'Venezuela'),
    ('UY', 'Uruguay', 'Uruguay'),
    ('CR', 'Costa Rica', 'Costa Rica'),
    ('PA', 'Panama', 'Panamá'),
    ('DO', 'Dominican Republic', 'República Dominicana'),
    ('CU', 'Cuba', 'Cuba'),
    ('PR', 'Puerto Rico', 'Puerto Rico'),
    ('IS', 'Iceland', 'Ísland'),
    ('BE', 'Belgium', 'België'),
    ('CH', 'Switzerland', 'Schweiz'),
    ('AT', 'Austria', 'Österreich'),
    ('PL', 'Poland', 'Polska'),
    ('CZ', 'Czech Republic', 'Česká republika'),
    ('HU', 'Hungary', 'Magyarország'),
    ('RO', 'Romania', 'România'),
    ('GR', 'Greece', 'Ελλάδα'),
    ('PT', 'Portugal', 'Portugal'),
    ('FI', 'Finland', 'Suomi'),
    ('NL', 'Netherlands', 'Nederland'),
    ('LU', 'Luxembourg', 'Luxembourg'),
    ('SK', 'Slovakia', 'Slovensko'),
    ('BG', 'Bulgaria', 'България'),
    ('HR', 'Croatia', 'Hrvatska'),
    ('SI', 'Slovenia', 'Slovenija'),
    ('RS', 'Serbia', 'Srbija'),
    ('UA', 'Ukraine', 'Україна'),
    ('BY', 'Belarus', 'Беларусь'),
    ('EE', 'Estonia', 'Eesti'),
    ('LV', 'Latvia', 'Latvija'),
    ('LT', 'Lithuania', 'Lietuva'),
    ('GE', 'Georgia', 'საქართველო'),
    ('AM', 'Armenia', 'Հայաստան'),
    ('AZ', 'Azerbaijan', 'Azərbaycan'),
    ('KZ', 'Kazakhstan', 'Қазақстан'),
    ('UZ', 'Uzbekistan', 'Oʻzbekiston'),
    ('AF', 'Afghanistan', 'افغانستان'),
    ('PK', 'Pakistan', 'پاکستان'),
    ('BD', 'Bangladesh', 'বাংলাদেশ'),
    ('LK', 'Sri Lanka', 'ශ්‍රී ලංකා'),
    ('NP', 'Nepal', 'नेपाल'),
    ('MM', 'Myanmar', 'မြန်မာ'),
    ('KH', 'Cambodia', 'កម្ពុជា'),
    ('LA', 'Laos', 'ລາວ'),
    ('MN', 'Mongolia', 'Монгол')
ON CONFLICT (iso_3166_1) DO NOTHING;

-- Languages (ISO 639-1 codes)
INSERT INTO languages (iso_639_1, english_name, name) VALUES
    ('en', 'English', 'English'),
    ('es', 'Spanish', 'Español'),
    ('fr', 'French', 'Français'),
    ('de', 'German', 'Deutsch'),
    ('it', 'Italian', 'Italiano'),
    ('ja', 'Japanese', '日本語'),
    ('ko', 'Korean', '한국어'),
    ('zh', 'Chinese', '中文'),
    ('pt', 'Portuguese', 'Português'),
    ('ru', 'Russian', 'Русский'),
    ('hi', 'Hindi', 'हिन्दी'),
    ('ar', 'Arabic', 'العربية'),
    ('nl', 'Dutch', 'Nederlands'),
    ('sv', 'Swedish', 'Svenska'),
    ('no', 'Norwegian', 'Norsk'),
    ('da', 'Danish', 'Dansk'),
    ('fi', 'Finnish', 'Suomi'),
    ('pl', 'Polish', 'Polski'),
    ('tr', 'Turkish', 'Türkçe'),
    ('he', 'Hebrew', 'עברית'),
    ('id', 'Indonesian', 'Bahasa Indonesia'),
    ('th', 'Thai', 'ภาษาไทย'),
    ('vi', 'Vietnamese', 'Tiếng Việt'),
    ('tl', 'Tagalog', 'Tagalog'),
    ('ms', 'Malay', 'Bahasa Melayu'),
    ('fa', 'Persian', 'فارسی'),
    ('ur', 'Urdu', 'اردو'),
    ('bn', 'Bengali', 'বাংলা'),
    ('ta', 'Tamil', 'தமிழ்'),
    ('te', 'Telugu', 'తెలుగు'),
    ('el', 'Greek', 'Ελληνικά'),
    ('cs', 'Czech', 'Čeština'),
    ('hu', 'Hungarian', 'Magyar'),
    ('ro', 'Romanian', 'Română'),
    ('uk', 'Ukrainian', 'Українська'),
    ('bg', 'Bulgarian', 'Български'),
    ('hr', 'Croatian', 'Hrvatski'),
    ('sr', 'Serbian', 'Српски'),
    ('sk', 'Slovak', 'Slovenčina'),
    ('sl', 'Slovenian', 'Slovenščina'),
    ('et', 'Estonian', 'Eesti'),
    ('lv', 'Latvian', 'Latviešu'),
    ('lt', 'Lithuanian', 'Lietuvių'),
    ('is', 'Icelandic', 'Íslenska'),
    ('ga', 'Irish', 'Gaeilge'),
    ('cy', 'Welsh', 'Cymraeg'),
    ('eu', 'Basque', 'Euskara'),
    ('ca', 'Catalan', 'Català'),
    ('gl', 'Galician', 'Galego'),
    ('mk', 'Macedonian', 'Македонски'),
    ('sq', 'Albanian', 'Shqip'),
    ('bs', 'Bosnian', 'Bosanski'),
    ('ka', 'Georgian', 'ქართული'),
    ('hy', 'Armenian', 'Հայերեն'),
    ('az', 'Azerbaijani', 'Azərbaycanca'),
    ('kk', 'Kazakh', 'Қазақша'),
    ('uz', 'Uzbek', 'Oʻzbekcha'),
    ('ky', 'Kyrgyz', 'Кыргызча'),
    ('tg', 'Tajik', 'Тоҷикӣ'),
    ('tk', 'Turkmen', 'Türkmençe'),
    ('mn', 'Mongolian', 'Монгол'),
    ('my', 'Burmese', 'မြန်မာ'),
    ('km', 'Khmer', 'ភាសាខ្មែរ'),
    ('lo', 'Lao', 'ລາວ'),
    ('si', 'Sinhala', 'සිංහල'),
    ('ne', 'Nepali', 'नेपाली'),
    ('ps', 'Pashto', 'پښتو'),
    ('ku', 'Kurdish', 'Kurdî'),
    ('sd', 'Sindhi', 'سنڌي'),
    ('yi', 'Yiddish', 'ייִדיש'),
    ('af', 'Afrikaans', 'Afrikaans'),
    ('am', 'Amharic', 'አማርኛ'),
    ('sw', 'Swahili', 'Kiswahili'),
    ('zu', 'Zulu', 'isiZulu'),
    ('xh', 'Xhosa', 'isiXhosa'),
    ('st', 'Sesotho', 'Sesotho'),
    ('so', 'Somali', 'Soomaali'),
    ('ha', 'Hausa', 'Hausa'),
    ('yo', 'Yoruba', 'Yorùbá'),
    ('ig', 'Igbo', 'Igbo'),
    ('ml', 'Malayalam', 'മലയാളം'),
    ('kn', 'Kannada', 'ಕನ್ನಡ'),
    ('mr', 'Marathi', 'मराठी'),
    ('gu', 'Gujarati', 'ગુજરાતી'),
    ('pa', 'Punjabi', 'ਪੰਜਾਬੀ'),
    ('or', 'Odia', 'ଓଡ଼ିଆ'),
    ('as', 'Assamese', 'অসমীয়া'),
    ('be', 'Belarusian', 'Беларуская'),
    ('lb', 'Luxembourgish', 'Lëtzebuergesch'),
    ('mt', 'Maltese', 'Malti'),
    ('fo', 'Faroese', 'Føroyskt')
ON CONFLICT (iso_639_1) DO NOTHING;

-- Genres (TMDB standard IDs)
INSERT INTO genres (genre_id, name) VALUES
    (28, 'Action'),
    (12, 'Adventure'),
    (16, 'Animation'),
    (35, 'Comedy'),
    (80, 'Crime'),
    (99, 'Documentary'),
    (18, 'Drama'),
    (10751, 'Family'),
    (14, 'Fantasy'),
    (36, 'History'),
    (27, 'Horror'),
    (10402, 'Music'),
    (9648, 'Mystery'),
    (10749, 'Romance'),
    (878, 'Science Fiction'),
    (10770, 'TV Movie'),
    (53, 'Thriller'),
    (10752, 'War'),
    (37, 'Western')
ON CONFLICT (genre_id) DO NOTHING;

-- Verify
SELECT 'countries' AS table_name, COUNT(*) AS row_count FROM countries
UNION ALL
SELECT 'languages', COUNT(*) FROM languages
UNION ALL
SELECT 'genres', COUNT(*) FROM genres;
